# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '历史详情.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Xiangqing(object):
    def setupUi(self, Xiangqing):
        Xiangqing.setObjectName("Xiangqing")
        Xiangqing.resize(1280, 720)
        Xiangqing.setMinimumSize(QtCore.QSize(1280, 720))
        Xiangqing.setMaximumSize(QtCore.QSize(1280, 720))
        Xiangqing.setStyleSheet("#Chupai{\n"
"border-image: url(:/.../background2.jpg);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Xiangqing)
        self.centralwidget.setObjectName("centralwidget")
        self.player1touxiang = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1touxiang.setGeometry(QtCore.QRect(50, 500, 70, 70))
        self.player1touxiang.setMinimumSize(QtCore.QSize(70, 70))
        self.player1touxiang.setMaximumSize(QtCore.QSize(70, 70))
        self.player1touxiang.setStyleSheet("#player1touxiang{\n"
"border-image: url(:/.../touxiang1.jpg);\n"
"}")
        self.player1touxiang.setMidLineWidth(0)
        self.player1touxiang.setObjectName("player1touxiang")
        self.player2puke1_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_1.setGeometry(QtCore.QRect(665, 20, 100, 150))
        self.player2puke1_1.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_1.setAutoFillBackground(False)
        self.player2puke1_1.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_1.setMidLineWidth(100)
        self.player2puke1_1.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_1.setObjectName("player2puke1_1")
        self.player2puke1_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_2.setGeometry(QtCore.QRect(690, 20, 100, 150))
        self.player2puke1_2.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_2.setAutoFillBackground(False)
        self.player2puke1_2.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_2.setMidLineWidth(100)
        self.player2puke1_2.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_2.setObjectName("player2puke1_2")
        self.player2puke1_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_3.setGeometry(QtCore.QRect(715, 20, 100, 150))
        self.player2puke1_3.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_3.setAutoFillBackground(False)
        self.player2puke1_3.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_3.setMidLineWidth(100)
        self.player2puke1_3.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_3.setObjectName("player2puke1_3")
        self.player2puke1_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_4.setGeometry(QtCore.QRect(640, 60, 100, 150))
        self.player2puke1_4.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_4.setAutoFillBackground(False)
        self.player2puke1_4.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_4.setMidLineWidth(100)
        self.player2puke1_4.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_4.setObjectName("player2puke1_4")
        self.player2puke1_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_5.setGeometry(QtCore.QRect(665, 60, 100, 150))
        self.player2puke1_5.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_5.setAutoFillBackground(False)
        self.player2puke1_5.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_5.setMidLineWidth(100)
        self.player2puke1_5.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_5.setObjectName("player2puke1_5")
        self.player2puke1_6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_6.setGeometry(QtCore.QRect(690, 60, 100, 150))
        self.player2puke1_6.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_6.setAutoFillBackground(False)
        self.player2puke1_6.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_6.setMidLineWidth(100)
        self.player2puke1_6.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_6.setObjectName("player2puke1_6")
        self.player2puke1_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_7.setGeometry(QtCore.QRect(715, 60, 100, 150))
        self.player2puke1_7.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_7.setAutoFillBackground(False)
        self.player2puke1_7.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_7.setMidLineWidth(100)
        self.player2puke1_7.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_7.setObjectName("player2puke1_7")
        self.player2puke1_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_8.setGeometry(QtCore.QRect(740, 60, 100, 150))
        self.player2puke1_8.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_8.setAutoFillBackground(False)
        self.player2puke1_8.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_8.setMidLineWidth(100)
        self.player2puke1_8.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_8.setObjectName("player2puke1_8")
        self.player2puke1_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_9.setGeometry(QtCore.QRect(610, 100, 100, 150))
        self.player2puke1_9.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_9.setAutoFillBackground(False)
        self.player2puke1_9.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_9.setMidLineWidth(100)
        self.player2puke1_9.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_9.setObjectName("player2puke1_9")
        self.player2puke1_10 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_10.setGeometry(QtCore.QRect(650, 100, 100, 150))
        self.player2puke1_10.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_10.setAutoFillBackground(False)
        self.player2puke1_10.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_10.setMidLineWidth(100)
        self.player2puke1_10.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_10.setObjectName("player2puke1_10")
        self.player2puke1_11 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_11.setGeometry(QtCore.QRect(690, 100, 100, 150))
        self.player2puke1_11.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_11.setAutoFillBackground(False)
        self.player2puke1_11.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_11.setMidLineWidth(100)
        self.player2puke1_11.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_11.setObjectName("player2puke1_11")
        self.player2puke1_12 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_12.setGeometry(QtCore.QRect(730, 100, 100, 150))
        self.player2puke1_12.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_12.setAutoFillBackground(False)
        self.player2puke1_12.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_12.setMidLineWidth(100)
        self.player2puke1_12.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_12.setObjectName("player2puke1_12")
        self.player2puke1_13 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_13.setGeometry(QtCore.QRect(770, 100, 100, 150))
        self.player2puke1_13.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_13.setAutoFillBackground(False)
        self.player2puke1_13.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_13.setMidLineWidth(100)
        self.player2puke1_13.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_13.setObjectName("player2puke1_13")
        self.player1touxiangkuang = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1touxiangkuang.setGeometry(QtCore.QRect(48, 498, 74, 74))
        self.player1touxiangkuang.setStyleSheet("#player1touxiangkuang{\n"
"border-image: url(:/.../touxiangkuang.png);\n"
"}\n"
"")
        self.player1touxiangkuang.setObjectName("player1touxiangkuang")
        self.player2touxiang = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2touxiang.setGeometry(QtCore.QRect(480, 50, 70, 70))
        self.player2touxiang.setMinimumSize(QtCore.QSize(70, 70))
        self.player2touxiang.setMaximumSize(QtCore.QSize(70, 70))
        self.player2touxiang.setStyleSheet("#player2touxiang{\n"
"border-image: url(:/.../touxiang2.jpg);\n"
"}")
        self.player2touxiang.setMidLineWidth(0)
        self.player2touxiang.setObjectName("player2touxiang")
        self.player2touxiangkuang = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2touxiangkuang.setGeometry(QtCore.QRect(478, 48, 74, 74))
        self.player2touxiangkuang.setMinimumSize(QtCore.QSize(74, 74))
        self.player2touxiangkuang.setMaximumSize(QtCore.QSize(74, 74))
        self.player2touxiangkuang.setStyleSheet("#player2touxiangkuang{\n"
"border-image: url(:/.../touxiangkuang.png);\n"
"}\n"
"")
        self.player2touxiangkuang.setObjectName("player2touxiangkuang")
        self.player3touxiang = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3touxiang.setGeometry(QtCore.QRect(1156, 80, 70, 70))
        self.player3touxiang.setMinimumSize(QtCore.QSize(70, 70))
        self.player3touxiang.setMaximumSize(QtCore.QSize(70, 70))
        self.player3touxiang.setStyleSheet("#player3touxiang{\n"
"border-image: url(:/.../touxiang3.png);\n"
"}\n"
"")
        self.player3touxiang.setObjectName("player3touxiang")
        self.player3touxiangkuang = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3touxiangkuang.setGeometry(QtCore.QRect(1154, 78, 74, 74))
        self.player3touxiangkuang.setMinimumSize(QtCore.QSize(74, 74))
        self.player3touxiangkuang.setMaximumSize(QtCore.QSize(74, 74))
        self.player3touxiangkuang.setStyleSheet("#player3touxiangkuang{\n"
"border-image: url(:/.../touxiangkuang.png);\n"
"}\n"
"")
        self.player3touxiangkuang.setObjectName("player3touxiangkuang")
        self.player3puke_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_1.setGeometry(QtCore.QRect(1070, 200, 100, 150))
        self.player3puke_1.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_1.setAutoFillBackground(False)
        self.player3puke_1.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_1.setMidLineWidth(100)
        self.player3puke_1.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_1.setObjectName("player3puke_1")
        self.touxiang = QtWidgets.QGraphicsView(self.centralwidget)
        self.touxiang.setGeometry(QtCore.QRect(850, 580, 90, 90))
        self.touxiang.setMinimumSize(QtCore.QSize(90, 90))
        self.touxiang.setMaximumSize(QtCore.QSize(90, 90))
        self.touxiang.setStyleSheet("#touxiang{\n"
"border-image: url(:/.../touxiang.jpg);\n"
"}")
        self.touxiang.setObjectName("touxiang")
        self.buttonfendun = QtWidgets.QPushButton(self.centralwidget)
        self.buttonfendun.setGeometry(QtCore.QRect(1020, 625, 118, 44))
        self.buttonfendun.setMinimumSize(QtCore.QSize(118, 44))
        self.buttonfendun.setMaximumSize(QtCore.QSize(118, 44))
        self.buttonfendun.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonfendun.setStyleSheet("#buttonfendun{\n"
"    font: 18pt \"华文新魏\";\n"
"    color: rgb(255, 255, 0);\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(234, 11, 11, 255));\n"
"}")
        self.buttonfendun.setObjectName("buttonfendun")
        self.touxiangkuang = QtWidgets.QGraphicsView(self.centralwidget)
        self.touxiangkuang.setGeometry(QtCore.QRect(847, 577, 98, 98))
        self.touxiangkuang.setMinimumSize(QtCore.QSize(98, 98))
        self.touxiangkuang.setMaximumSize(QtCore.QSize(98, 98))
        self.touxiangkuang.setStyleSheet("#touxiangkuang{\n"
"border-image: url(:/.../touxiangkuang.png);\n"
"}")
        self.touxiangkuang.setObjectName("touxiangkuang")
        self.mypuke_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_1.setGeometry(QtCore.QRect(460, 370, 120, 180))
        self.mypuke_1.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_1.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_1.setAutoFillBackground(False)
        self.mypuke_1.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_1.setMidLineWidth(100)
        self.mypuke_1.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_1.setObjectName("mypuke_1")
        self.mypuke_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_2.setGeometry(QtCore.QRect(500, 370, 120, 180))
        self.mypuke_2.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_2.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_2.setAutoFillBackground(False)
        self.mypuke_2.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_2.setMidLineWidth(100)
        self.mypuke_2.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_2.setObjectName("mypuke_2")
        self.mypuke_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_3.setGeometry(QtCore.QRect(540, 370, 120, 180))
        self.mypuke_3.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_3.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_3.setAutoFillBackground(False)
        self.mypuke_3.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_3.setMidLineWidth(100)
        self.mypuke_3.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_3.setObjectName("mypuke_3")
        self.mypuke_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_4.setGeometry(QtCore.QRect(420, 430, 120, 180))
        self.mypuke_4.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_4.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_4.setAutoFillBackground(False)
        self.mypuke_4.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_4.setMidLineWidth(100)
        self.mypuke_4.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_4.setObjectName("mypuke_4")
        self.mypuke_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_5.setGeometry(QtCore.QRect(460, 430, 120, 180))
        self.mypuke_5.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_5.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_5.setAutoFillBackground(False)
        self.mypuke_5.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_5.setMidLineWidth(100)
        self.mypuke_5.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_5.setObjectName("mypuke_5")
        self.mypuke_6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_6.setGeometry(QtCore.QRect(500, 430, 120, 180))
        self.mypuke_6.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_6.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_6.setAutoFillBackground(False)
        self.mypuke_6.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_6.setMidLineWidth(100)
        self.mypuke_6.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_6.setObjectName("mypuke_6")
        self.mypuke_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_7.setGeometry(QtCore.QRect(540, 430, 120, 180))
        self.mypuke_7.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_7.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_7.setAutoFillBackground(False)
        self.mypuke_7.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_7.setMidLineWidth(100)
        self.mypuke_7.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_7.setObjectName("mypuke_7")
        self.mypuke_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_8.setGeometry(QtCore.QRect(580, 430, 120, 180))
        self.mypuke_8.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_8.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_8.setAutoFillBackground(False)
        self.mypuke_8.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_8.setMidLineWidth(100)
        self.mypuke_8.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_8.setObjectName("mypuke_8")
        self.mypuke_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_9.setGeometry(QtCore.QRect(380, 490, 120, 180))
        self.mypuke_9.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_9.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_9.setAutoFillBackground(False)
        self.mypuke_9.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_9.setMidLineWidth(100)
        self.mypuke_9.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_9.setObjectName("mypuke_9")
        self.mypuke_10 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_10.setGeometry(QtCore.QRect(440, 490, 120, 180))
        self.mypuke_10.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_10.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_10.setAutoFillBackground(False)
        self.mypuke_10.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_10.setMidLineWidth(100)
        self.mypuke_10.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_10.setObjectName("mypuke_10")
        self.mypuke_11 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_11.setGeometry(QtCore.QRect(500, 490, 120, 180))
        self.mypuke_11.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_11.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_11.setAutoFillBackground(False)
        self.mypuke_11.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_11.setMidLineWidth(100)
        self.mypuke_11.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_11.setObjectName("mypuke_11")
        self.mypuke_12 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_12.setGeometry(QtCore.QRect(560, 490, 120, 180))
        self.mypuke_12.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_12.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_12.setAutoFillBackground(False)
        self.mypuke_12.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_12.setMidLineWidth(100)
        self.mypuke_12.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_12.setObjectName("mypuke_12")
        self.mypuke_13 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_13.setGeometry(QtCore.QRect(620, 490, 120, 180))
        self.mypuke_13.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_13.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_13.setAutoFillBackground(False)
        self.mypuke_13.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_13.setMidLineWidth(100)
        self.mypuke_13.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_13.setObjectName("mypuke_13")
        self.player3puke_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_2.setGeometry(QtCore.QRect(1095, 200, 100, 150))
        self.player3puke_2.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_2.setAutoFillBackground(False)
        self.player3puke_2.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_2.setMidLineWidth(100)
        self.player3puke_2.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_2.setObjectName("player3puke_2")
        self.player3puke_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_3.setGeometry(QtCore.QRect(1120, 200, 100, 150))
        self.player3puke_3.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_3.setAutoFillBackground(False)
        self.player3puke_3.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_3.setMidLineWidth(100)
        self.player3puke_3.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_3.setObjectName("player3puke_3")
        self.player3puke1_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke1_8.setGeometry(QtCore.QRect(1140, 240, 100, 150))
        self.player3puke1_8.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke1_8.setAutoFillBackground(False)
        self.player3puke1_8.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke1_8.setMidLineWidth(100)
        self.player3puke1_8.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke1_8.setObjectName("player3puke1_8")
        self.player3puke1_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke1_4.setGeometry(QtCore.QRect(1040, 240, 100, 150))
        self.player3puke1_4.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke1_4.setAutoFillBackground(False)
        self.player3puke1_4.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke1_4.setMidLineWidth(100)
        self.player3puke1_4.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke1_4.setObjectName("player3puke1_4")
        self.player3puke1_6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke1_6.setGeometry(QtCore.QRect(1090, 240, 100, 150))
        self.player3puke1_6.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke1_6.setAutoFillBackground(False)
        self.player3puke1_6.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke1_6.setMidLineWidth(100)
        self.player3puke1_6.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke1_6.setObjectName("player3puke1_6")
        self.player3puke1_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke1_5.setGeometry(QtCore.QRect(1065, 240, 100, 150))
        self.player3puke1_5.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke1_5.setAutoFillBackground(False)
        self.player3puke1_5.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke1_5.setMidLineWidth(100)
        self.player3puke1_5.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke1_5.setObjectName("player3puke1_5")
        self.player3puke1_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke1_7.setGeometry(QtCore.QRect(1115, 240, 100, 150))
        self.player3puke1_7.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke1_7.setAutoFillBackground(False)
        self.player3puke1_7.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke1_7.setMidLineWidth(100)
        self.player3puke1_7.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke1_7.setObjectName("player3puke1_7")
        self.player3puke1_10 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke1_10.setGeometry(QtCore.QRect(1050, 280, 100, 150))
        self.player3puke1_10.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke1_10.setAutoFillBackground(False)
        self.player3puke1_10.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke1_10.setMidLineWidth(100)
        self.player3puke1_10.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke1_10.setObjectName("player3puke1_10")
        self.player3puke1_11 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke1_11.setGeometry(QtCore.QRect(1090, 280, 100, 150))
        self.player3puke1_11.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke1_11.setAutoFillBackground(False)
        self.player3puke1_11.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke1_11.setMidLineWidth(100)
        self.player3puke1_11.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke1_11.setObjectName("player3puke1_11")
        self.player3puke1_12 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke1_12.setGeometry(QtCore.QRect(1130, 280, 100, 150))
        self.player3puke1_12.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke1_12.setAutoFillBackground(False)
        self.player3puke1_12.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke1_12.setMidLineWidth(100)
        self.player3puke1_12.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke1_12.setObjectName("player3puke1_12")
        self.player3puke1_13 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke1_13.setGeometry(QtCore.QRect(1170, 280, 100, 150))
        self.player3puke1_13.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke1_13.setAutoFillBackground(False)
        self.player3puke1_13.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke1_13.setMidLineWidth(100)
        self.player3puke1_13.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke1_13.setObjectName("player3puke1_13")
        self.player3puke1_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke1_9.setGeometry(QtCore.QRect(1010, 280, 100, 150))
        self.player3puke1_9.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke1_9.setAutoFillBackground(False)
        self.player3puke1_9.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke1_9.setMidLineWidth(100)
        self.player3puke1_9.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke1_9.setObjectName("player3puke1_9")
        self.player1puke_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke_1.setGeometry(QtCore.QRect(80, 210, 100, 150))
        self.player1puke_1.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke_1.setAutoFillBackground(False)
        self.player1puke_1.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke_1.setMidLineWidth(100)
        self.player1puke_1.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke_1.setObjectName("player1puke_1")
        self.player1puke1_12 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_12.setGeometry(QtCore.QRect(140, 290, 100, 150))
        self.player1puke1_12.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_12.setAutoFillBackground(False)
        self.player1puke1_12.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_12.setMidLineWidth(100)
        self.player1puke1_12.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_12.setObjectName("player1puke1_12")
        self.player1puke1_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_5.setGeometry(QtCore.QRect(75, 250, 100, 150))
        self.player1puke1_5.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_5.setAutoFillBackground(False)
        self.player1puke1_5.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_5.setMidLineWidth(100)
        self.player1puke1_5.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_5.setObjectName("player1puke1_5")
        self.player1puke1_16 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_16.setGeometry(QtCore.QRect(180, 290, 100, 150))
        self.player1puke1_16.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_16.setAutoFillBackground(False)
        self.player1puke1_16.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_16.setMidLineWidth(100)
        self.player1puke1_16.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_16.setObjectName("player1puke1_16")
        self.player1puke_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke_2.setGeometry(QtCore.QRect(105, 210, 100, 150))
        self.player1puke_2.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke_2.setAutoFillBackground(False)
        self.player1puke_2.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke_2.setMidLineWidth(100)
        self.player1puke_2.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke_2.setObjectName("player1puke_2")
        self.player1puke1_6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_6.setGeometry(QtCore.QRect(100, 250, 100, 150))
        self.player1puke1_6.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_6.setAutoFillBackground(False)
        self.player1puke1_6.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_6.setMidLineWidth(100)
        self.player1puke1_6.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_6.setObjectName("player1puke1_6")
        self.player1puke1_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_7.setGeometry(QtCore.QRect(125, 250, 100, 150))
        self.player1puke1_7.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_7.setAutoFillBackground(False)
        self.player1puke1_7.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_7.setMidLineWidth(100)
        self.player1puke1_7.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_7.setObjectName("player1puke1_7")
        self.player1puke1_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_9.setGeometry(QtCore.QRect(20, 290, 100, 150))
        self.player1puke1_9.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_9.setAutoFillBackground(False)
        self.player1puke1_9.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_9.setMidLineWidth(100)
        self.player1puke1_9.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_9.setObjectName("player1puke1_9")
        self.player1puke1_10 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_10.setGeometry(QtCore.QRect(60, 290, 100, 150))
        self.player1puke1_10.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_10.setAutoFillBackground(False)
        self.player1puke1_10.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_10.setMidLineWidth(100)
        self.player1puke1_10.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_10.setObjectName("player1puke1_10")
        self.player1puke_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke_3.setGeometry(QtCore.QRect(130, 210, 100, 150))
        self.player1puke_3.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke_3.setAutoFillBackground(False)
        self.player1puke_3.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke_3.setMidLineWidth(100)
        self.player1puke_3.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke_3.setObjectName("player1puke_3")
        self.player1puke1_11 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_11.setGeometry(QtCore.QRect(100, 290, 100, 150))
        self.player1puke1_11.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_11.setAutoFillBackground(False)
        self.player1puke1_11.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_11.setMidLineWidth(100)
        self.player1puke1_11.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_11.setObjectName("player1puke1_11")
        self.player1puke1_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_8.setGeometry(QtCore.QRect(150, 250, 100, 150))
        self.player1puke1_8.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_8.setAutoFillBackground(False)
        self.player1puke1_8.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_8.setMidLineWidth(100)
        self.player1puke1_8.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_8.setObjectName("player1puke1_8")
        self.player1puke1_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_4.setGeometry(QtCore.QRect(50, 250, 100, 150))
        self.player1puke1_4.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_4.setAutoFillBackground(False)
        self.player1puke1_4.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_4.setMidLineWidth(100)
        self.player1puke1_4.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_4.setObjectName("player1puke1_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(180, -10, 261, 201))
        self.graphicsView.setStyleSheet("border-image: url(:/.../logo4.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.ID_1 = QtWidgets.QLabel(self.centralwidget)
        self.ID_1.setGeometry(QtCore.QRect(50, 600, 71, 31))
        self.ID_1.setStyleSheet("font: 20pt \"华文新魏\";\n"
"color: rgb(255, 255, 255);")
        self.ID_1.setText("")
        self.ID_1.setObjectName("ID_1")
        self.ID_2 = QtWidgets.QLabel(self.centralwidget)
        self.ID_2.setGeometry(QtCore.QRect(480, 148, 71, 31))
        self.ID_2.setStyleSheet("font: 20pt \"华文新魏\";\n"
"color: rgb(255, 255, 255);")
        self.ID_2.setText("")
        self.ID_2.setObjectName("ID_2")
        self.ID_3 = QtWidgets.QLabel(self.centralwidget)
        self.ID_3.setGeometry(QtCore.QRect(1050, 120, 71, 31))
        self.ID_3.setStyleSheet("font: 20pt \"华文新魏\";\n"
"color: rgb(255, 255, 255);")
        self.ID_3.setText("")
        self.ID_3.setObjectName("ID_3")
        self.ID_4 = QtWidgets.QLabel(self.centralwidget)
        self.ID_4.setGeometry(QtCore.QRect(850, 520, 71, 31))
        self.ID_4.setStyleSheet("font: 20pt \"华文新魏\";\n"
"color: rgb(255, 255, 255);")
        self.ID_4.setText("")
        self.ID_4.setObjectName("ID_4")
        self.player1puke_1.raise_()
        self.player1puke_2.raise_()
        self.player1puke_3.raise_()
        self.player1puke1_4.raise_()
        self.player1puke1_5.raise_()
        self.player1puke1_6.raise_()
        self.player1puke1_7.raise_()
        self.player1puke1_8.raise_()
        self.player1puke1_9.raise_()
        self.player1puke1_10.raise_()
        self.player1puke1_11.raise_()
        self.player1puke1_12.raise_()
        self.player1puke1_16.raise_()
        self.player3puke1_4.raise_()
        self.player3puke_1.raise_()
        self.player3puke_2.raise_()
        self.player1touxiang.raise_()
        self.player2puke1_1.raise_()
        self.player2puke1_2.raise_()
        self.player2puke1_3.raise_()
        self.player2puke1_4.raise_()
        self.player2puke1_5.raise_()
        self.player2puke1_6.raise_()
        self.player2puke1_7.raise_()
        self.player2puke1_8.raise_()
        self.player2puke1_9.raise_()
        self.player2puke1_10.raise_()
        self.player2puke1_11.raise_()
        self.player2puke1_12.raise_()
        self.player2puke1_13.raise_()
        self.player1touxiangkuang.raise_()
        self.player2touxiang.raise_()
        self.player2touxiangkuang.raise_()
        self.player3touxiang.raise_()
        self.player3touxiangkuang.raise_()
        self.touxiang.raise_()
        self.buttonfendun.raise_()
        self.touxiangkuang.raise_()
        self.mypuke_1.raise_()
        self.mypuke_2.raise_()
        self.mypuke_3.raise_()
        self.mypuke_4.raise_()
        self.mypuke_5.raise_()
        self.mypuke_6.raise_()
        self.mypuke_7.raise_()
        self.mypuke_8.raise_()
        self.mypuke_9.raise_()
        self.mypuke_10.raise_()
        self.mypuke_11.raise_()
        self.mypuke_12.raise_()
        self.mypuke_13.raise_()
        self.player3puke_3.raise_()
        self.player3puke1_5.raise_()
        self.player3puke1_6.raise_()
        self.player3puke1_7.raise_()
        self.player3puke1_8.raise_()
        self.player3puke1_9.raise_()
        self.player3puke1_10.raise_()
        self.player3puke1_11.raise_()
        self.player3puke1_12.raise_()
        self.player3puke1_13.raise_()
        self.graphicsView.raise_()
        self.ID_1.raise_()
        self.ID_2.raise_()
        self.ID_3.raise_()
        self.ID_4.raise_()
        Xiangqing.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Xiangqing)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 23))
        self.menubar.setObjectName("menubar")
        Xiangqing.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Xiangqing)
        self.statusbar.setObjectName("statusbar")
        Xiangqing.setStatusBar(self.statusbar)

        self.retranslateUi(Xiangqing)
        QtCore.QMetaObject.connectSlotsByName(Xiangqing)

    def retranslateUi(self, Xiangqing):
        _translate = QtCore.QCoreApplication.translate
        Xiangqing.setWindowTitle(_translate("Xiangqing", "History"))
        self.buttonfendun.setText(_translate("Xiangqing", "返回"))
import IMG
