# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '开始游戏.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Startgame(object):
    def setupUi(self, Startgame):
        Startgame.setObjectName("Startgame")
        Startgame.resize(1280, 720)
        Startgame.setMinimumSize(QtCore.QSize(1280, 720))
        Startgame.setMaximumSize(QtCore.QSize(1280, 720))
        Startgame.setStyleSheet("#Startgame{\n"
                                "border-image: url(:/.../background2.jpg);\n"
                                "}")
        self.centralwidget = QtWidgets.QWidget(Startgame)
        self.centralwidget.setObjectName("centralwidget")
        self.player1puke_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke_1.setGeometry(QtCore.QRect(50, 50, 100, 150))
        self.player1puke_1.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke_1.setAutoFillBackground(False)
        self.player1puke_1.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke_1.setMidLineWidth(100)
        self.player1puke_1.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke_1.setObjectName("player1puke_1")
        self.player1puke1_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_2.setGeometry(QtCore.QRect(50, 70, 100, 150))
        self.player1puke1_2.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_2.setAutoFillBackground(False)
        self.player1puke1_2.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_2.setMidLineWidth(100)
        self.player1puke1_2.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_2.setObjectName("player1puke1_2")
        self.player1puke1_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_3.setGeometry(QtCore.QRect(50, 90, 100, 150))
        self.player1puke1_3.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_3.setAutoFillBackground(False)
        self.player1puke1_3.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_3.setMidLineWidth(100)
        self.player1puke1_3.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_3.setObjectName("player1puke1_3")
        self.player1puke1_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_4.setGeometry(QtCore.QRect(50, 110, 100, 150))
        self.player1puke1_4.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_4.setAutoFillBackground(False)
        self.player1puke1_4.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_4.setMidLineWidth(100)
        self.player1puke1_4.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_4.setObjectName("player1puke1_4")
        self.player1puke1_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_5.setGeometry(QtCore.QRect(50, 130, 100, 150))
        self.player1puke1_5.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_5.setAutoFillBackground(False)
        self.player1puke1_5.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_5.setMidLineWidth(100)
        self.player1puke1_5.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_5.setObjectName("player1puke1_5")
        self.player1puke1_6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_6.setGeometry(QtCore.QRect(50, 150, 100, 150))
        self.player1puke1_6.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_6.setAutoFillBackground(False)
        self.player1puke1_6.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_6.setMidLineWidth(100)
        self.player1puke1_6.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_6.setObjectName("player1puke1_6")
        self.player1puke1_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_7.setGeometry(QtCore.QRect(50, 170, 100, 150))
        self.player1puke1_7.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_7.setAutoFillBackground(False)
        self.player1puke1_7.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_7.setMidLineWidth(100)
        self.player1puke1_7.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_7.setObjectName("player1puke1_7")
        self.player1puke1_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_8.setGeometry(QtCore.QRect(50, 190, 100, 150))
        self.player1puke1_8.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_8.setAutoFillBackground(False)
        self.player1puke1_8.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_8.setMidLineWidth(100)
        self.player1puke1_8.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_8.setObjectName("player1puke1_8")
        self.player1puke1_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_9.setGeometry(QtCore.QRect(50, 210, 100, 150))
        self.player1puke1_9.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_9.setAutoFillBackground(False)
        self.player1puke1_9.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_9.setMidLineWidth(100)
        self.player1puke1_9.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_9.setObjectName("player1puke1_9")
        self.player1puke1_10 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_10.setGeometry(QtCore.QRect(50, 230, 100, 150))
        self.player1puke1_10.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_10.setAutoFillBackground(False)
        self.player1puke1_10.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_10.setMidLineWidth(100)
        self.player1puke1_10.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_10.setObjectName("player1puke1_10")
        self.player1puke1_11 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_11.setGeometry(QtCore.QRect(50, 250, 100, 150))
        self.player1puke1_11.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_11.setAutoFillBackground(False)
        self.player1puke1_11.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_11.setMidLineWidth(100)
        self.player1puke1_11.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_11.setObjectName("player1puke1_11")
        self.player1puke1_12 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_12.setGeometry(QtCore.QRect(50, 270, 100, 150))
        self.player1puke1_12.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_12.setAutoFillBackground(False)
        self.player1puke1_12.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_12.setMidLineWidth(100)
        self.player1puke1_12.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_12.setObjectName("player1puke1_12")
        self.player1puke1_13 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1puke1_13.setGeometry(QtCore.QRect(50, 290, 100, 150))
        self.player1puke1_13.setMaximumSize(QtCore.QSize(100, 150))
        self.player1puke1_13.setAutoFillBackground(False)
        self.player1puke1_13.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player1puke1_13.setMidLineWidth(100)
        self.player1puke1_13.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player1puke1_13.setObjectName("player1puke1_13")
        self.player1touxiang = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1touxiang.setGeometry(QtCore.QRect(50, 500, 70, 70))
        self.player1touxiang.setMinimumSize(QtCore.QSize(70, 70))
        self.player1touxiang.setMaximumSize(QtCore.QSize(70, 70))
        self.player1touxiang.setStyleSheet("#player1touxiang{\n"
                                           "border-image: url(:/.../touxiang1.jpg);\n"
                                           "}")
        self.player1touxiang.setMidLineWidth(0)
        self.player1touxiang.setObjectName("player1touxiang")
        self.player2puke1_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_1.setGeometry(QtCore.QRect(600, 50, 100, 150))
        self.player2puke1_1.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_1.setAutoFillBackground(False)
        self.player2puke1_1.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_1.setMidLineWidth(100)
        self.player2puke1_1.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_1.setObjectName("player2puke1_1")
        self.player2puke1_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_2.setGeometry(QtCore.QRect(625, 50, 100, 150))
        self.player2puke1_2.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_2.setAutoFillBackground(False)
        self.player2puke1_2.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_2.setMidLineWidth(100)
        self.player2puke1_2.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_2.setObjectName("player2puke1_2")
        self.player2puke1_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_3.setGeometry(QtCore.QRect(650, 50, 100, 150))
        self.player2puke1_3.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_3.setAutoFillBackground(False)
        self.player2puke1_3.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_3.setMidLineWidth(100)
        self.player2puke1_3.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_3.setObjectName("player2puke1_3")
        self.player2puke1_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_4.setGeometry(QtCore.QRect(675, 50, 100, 150))
        self.player2puke1_4.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_4.setAutoFillBackground(False)
        self.player2puke1_4.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_4.setMidLineWidth(100)
        self.player2puke1_4.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_4.setObjectName("player2puke1_4")
        self.player2puke1_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_5.setGeometry(QtCore.QRect(700, 50, 100, 150))
        self.player2puke1_5.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_5.setAutoFillBackground(False)
        self.player2puke1_5.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_5.setMidLineWidth(100)
        self.player2puke1_5.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_5.setObjectName("player2puke1_5")
        self.player2puke1_6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_6.setGeometry(QtCore.QRect(725, 50, 100, 150))
        self.player2puke1_6.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_6.setAutoFillBackground(False)
        self.player2puke1_6.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_6.setMidLineWidth(100)
        self.player2puke1_6.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_6.setObjectName("player2puke1_6")
        self.player2puke1_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_7.setGeometry(QtCore.QRect(750, 50, 100, 150))
        self.player2puke1_7.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_7.setAutoFillBackground(False)
        self.player2puke1_7.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_7.setMidLineWidth(100)
        self.player2puke1_7.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_7.setObjectName("player2puke1_7")
        self.player2puke1_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_8.setGeometry(QtCore.QRect(775, 50, 100, 150))
        self.player2puke1_8.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_8.setAutoFillBackground(False)
        self.player2puke1_8.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_8.setMidLineWidth(100)
        self.player2puke1_8.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_8.setObjectName("player2puke1_8")
        self.player2puke1_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_9.setGeometry(QtCore.QRect(800, 50, 100, 150))
        self.player2puke1_9.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_9.setAutoFillBackground(False)
        self.player2puke1_9.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_9.setMidLineWidth(100)
        self.player2puke1_9.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_9.setObjectName("player2puke1_9")
        self.player2puke1_10 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_10.setGeometry(QtCore.QRect(825, 50, 100, 150))
        self.player2puke1_10.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_10.setAutoFillBackground(False)
        self.player2puke1_10.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_10.setMidLineWidth(100)
        self.player2puke1_10.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_10.setObjectName("player2puke1_10")
        self.player2puke1_11 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_11.setGeometry(QtCore.QRect(850, 50, 100, 150))
        self.player2puke1_11.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_11.setAutoFillBackground(False)
        self.player2puke1_11.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_11.setMidLineWidth(100)
        self.player2puke1_11.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_11.setObjectName("player2puke1_11")
        self.player2puke1_12 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_12.setGeometry(QtCore.QRect(875, 50, 100, 150))
        self.player2puke1_12.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_12.setAutoFillBackground(False)
        self.player2puke1_12.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_12.setMidLineWidth(100)
        self.player2puke1_12.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_12.setObjectName("player2puke1_12")
        self.player2puke1_13 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2puke1_13.setGeometry(QtCore.QRect(900, 50, 100, 150))
        self.player2puke1_13.setMaximumSize(QtCore.QSize(100, 150))
        self.player2puke1_13.setAutoFillBackground(False)
        self.player2puke1_13.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player2puke1_13.setMidLineWidth(100)
        self.player2puke1_13.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player2puke1_13.setObjectName("player2puke1_13")
        self.player1touxiangkuang = QtWidgets.QGraphicsView(self.centralwidget)
        self.player1touxiangkuang.setGeometry(QtCore.QRect(48, 498, 74, 74))
        self.player1touxiangkuang.setStyleSheet("#player1touxiangkuang{\n"
                                                "border-image: url(:/.../touxiangkuang.png);\n"
                                                "}\n"
                                                "")
        self.player1touxiangkuang.setObjectName("player1touxiangkuang")
        self.player2touxiang = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2touxiang.setGeometry(QtCore.QRect(480, 50, 70, 70))
        self.player2touxiang.setMinimumSize(QtCore.QSize(70, 70))
        self.player2touxiang.setMaximumSize(QtCore.QSize(70, 70))
        self.player2touxiang.setStyleSheet("#player2touxiang{\n"
                                           "border-image: url(:/.../touxiang2.jpg);\n"
                                           "}")
        self.player2touxiang.setMidLineWidth(0)
        self.player2touxiang.setObjectName("player2touxiang")
        self.player2touxiangkuang = QtWidgets.QGraphicsView(self.centralwidget)
        self.player2touxiangkuang.setGeometry(QtCore.QRect(478, 48, 74, 74))
        self.player2touxiangkuang.setMinimumSize(QtCore.QSize(74, 74))
        self.player2touxiangkuang.setMaximumSize(QtCore.QSize(74, 74))
        self.player2touxiangkuang.setStyleSheet("#player2touxiangkuang{\n"
                                                "border-image: url(:/.../touxiangkuang.png);\n"
                                                "}\n"
                                                "")
        self.player2touxiangkuang.setObjectName("player2touxiangkuang")
        self.player3puke_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_1.setGeometry(QtCore.QRect(1130, 200, 100, 150))
        self.player3puke_1.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_1.setAutoFillBackground(False)
        self.player3puke_1.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_1.setMidLineWidth(100)
        self.player3puke_1.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_1.setObjectName("player3puke_1")
        self.player3touxiang = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3touxiang.setGeometry(QtCore.QRect(1156, 80, 70, 70))
        self.player3touxiang.setMinimumSize(QtCore.QSize(70, 70))
        self.player3touxiang.setMaximumSize(QtCore.QSize(70, 70))
        self.player3touxiang.setStyleSheet("#player3touxiang{\n"
                                           "border-image: url(:/.../touxiang3.png);\n"
                                           "}\n"
                                           "")
        self.player3touxiang.setObjectName("player3touxiang")
        self.player3touxiangkuang = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3touxiangkuang.setGeometry(QtCore.QRect(1154, 78, 74, 74))
        self.player3touxiangkuang.setMinimumSize(QtCore.QSize(74, 74))
        self.player3touxiangkuang.setMaximumSize(QtCore.QSize(74, 74))
        self.player3touxiangkuang.setStyleSheet("#player3touxiangkuang{\n"
                                                "border-image: url(:/.../touxiangkuang.png);\n"
                                                "}\n"
                                                "")
        self.player3touxiangkuang.setObjectName("player3touxiangkuang")
        self.player3puke_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_2.setGeometry(QtCore.QRect(1130, 220, 100, 150))
        self.player3puke_2.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_2.setAutoFillBackground(False)
        self.player3puke_2.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_2.setMidLineWidth(100)
        self.player3puke_2.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_2.setObjectName("player3puke_2")
        self.player3puke_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_3.setGeometry(QtCore.QRect(1130, 240, 100, 150))
        self.player3puke_3.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_3.setAutoFillBackground(False)
        self.player3puke_3.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_3.setMidLineWidth(100)
        self.player3puke_3.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_3.setObjectName("player3puke_3")
        self.player3puke_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_4.setGeometry(QtCore.QRect(1130, 260, 100, 150))
        self.player3puke_4.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_4.setAutoFillBackground(False)
        self.player3puke_4.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_4.setMidLineWidth(100)
        self.player3puke_4.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_4.setObjectName("player3puke_4")
        self.player3puke_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_5.setGeometry(QtCore.QRect(1130, 280, 100, 150))
        self.player3puke_5.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_5.setAutoFillBackground(False)
        self.player3puke_5.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_5.setMidLineWidth(100)
        self.player3puke_5.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_5.setObjectName("player3puke_5")
        self.player3puke_6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_6.setGeometry(QtCore.QRect(1130, 300, 100, 150))
        self.player3puke_6.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_6.setAutoFillBackground(False)
        self.player3puke_6.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_6.setMidLineWidth(100)
        self.player3puke_6.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_6.setObjectName("player3puke_6")
        self.player3puke_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_7.setGeometry(QtCore.QRect(1130, 320, 100, 150))
        self.player3puke_7.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_7.setAutoFillBackground(False)
        self.player3puke_7.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_7.setMidLineWidth(100)
        self.player3puke_7.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_7.setObjectName("player3puke_7")
        self.player3puke_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_8.setGeometry(QtCore.QRect(1130, 340, 100, 150))
        self.player3puke_8.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_8.setAutoFillBackground(False)
        self.player3puke_8.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_8.setMidLineWidth(100)
        self.player3puke_8.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_8.setObjectName("player3puke_8")
        self.player3puke_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_9.setGeometry(QtCore.QRect(1130, 360, 100, 150))
        self.player3puke_9.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_9.setAutoFillBackground(False)
        self.player3puke_9.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_9.setMidLineWidth(100)
        self.player3puke_9.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_9.setObjectName("player3puke_9")
        self.player3puke_10 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_10.setGeometry(QtCore.QRect(1130, 380, 100, 150))
        self.player3puke_10.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_10.setAutoFillBackground(False)
        self.player3puke_10.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_10.setMidLineWidth(100)
        self.player3puke_10.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_10.setObjectName("player3puke_10")
        self.player3puke_11 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_11.setGeometry(QtCore.QRect(1130, 400, 100, 150))
        self.player3puke_11.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_11.setAutoFillBackground(False)
        self.player3puke_11.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_11.setMidLineWidth(100)
        self.player3puke_11.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_11.setObjectName("player3puke_11")
        self.player3puke_12 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_12.setGeometry(QtCore.QRect(1130, 420, 100, 150))
        self.player3puke_12.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_12.setAutoFillBackground(False)
        self.player3puke_12.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_12.setMidLineWidth(100)
        self.player3puke_12.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_12.setObjectName("player3puke_12")
        self.player3puke_13 = QtWidgets.QGraphicsView(self.centralwidget)
        self.player3puke_13.setGeometry(QtCore.QRect(1130, 440, 100, 150))
        self.player3puke_13.setMaximumSize(QtCore.QSize(100, 150))
        self.player3puke_13.setAutoFillBackground(False)
        self.player3puke_13.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.player3puke_13.setMidLineWidth(100)
        self.player3puke_13.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.player3puke_13.setObjectName("player3puke_13")
        self.touxiang = QtWidgets.QGraphicsView(self.centralwidget)
        self.touxiang.setGeometry(QtCore.QRect(850, 580, 90, 90))
        self.touxiang.setMinimumSize(QtCore.QSize(90, 90))
        self.touxiang.setMaximumSize(QtCore.QSize(90, 90))
        self.touxiang.setStyleSheet("#touxiang{\n"
                                    "border-image: url(:/.../touxiang.jpg);\n"
                                    "}")
        self.touxiang.setObjectName("touxiang")
        self.buttonfendun = QtWidgets.QPushButton(self.centralwidget)
        self.buttonfendun.setGeometry(QtCore.QRect(1020, 625, 118, 44))
        self.buttonfendun.setMinimumSize(QtCore.QSize(118, 44))
        self.buttonfendun.setMaximumSize(QtCore.QSize(118, 44))
        self.buttonfendun.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonfendun.setStyleSheet("#buttonfendun{\n"
                                        "    font: 18pt \"华文新魏\";\n"
                                        "    color: rgb(255, 255, 0);\n"
                                        "    border:none;\n"
                                        "    border-radius:8px;\n"
                                        "    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(234, 11, 11, 255));\n"
                                        "}")
        self.buttonfendun.setObjectName("buttonfendun")
        self.touxiangkuang = QtWidgets.QGraphicsView(self.centralwidget)
        self.touxiangkuang.setGeometry(QtCore.QRect(847, 577, 95, 95))
        self.touxiangkuang.setMaximumSize(QtCore.QSize(96, 96))
        self.touxiangkuang.setStyleSheet("#touxiangkuang{\n"
                                         "border-image: url(:/.../touxiangkuang.png);\n"
                                         "}")
        self.touxiangkuang.setObjectName("touxiangkuang")

        self.mypuke_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_1.setGeometry(QtCore.QRect(250, 490, 120, 180))
        self.mypuke_1.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_1.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_1.setAutoFillBackground(False)
        self.mypuke_1.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_1.setMidLineWidth(100)
        self.mypuke_1.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_1.setObjectName("mypuke_1")
        self.mypuke_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_2.setGeometry(QtCore.QRect(285, 490, 120, 180))
        self.mypuke_2.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_2.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_2.setAutoFillBackground(False)
        self.mypuke_2.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_2.setMidLineWidth(100)
        self.mypuke_2.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_2.setObjectName("mypuke_2")
        self.mypuke_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_3.setGeometry(QtCore.QRect(320, 490, 120, 180))
        self.mypuke_3.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_3.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_3.setAutoFillBackground(False)
        self.mypuke_3.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_3.setMidLineWidth(100)
        self.mypuke_3.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_3.setObjectName("mypuke_3")
        self.mypuke_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_4.setGeometry(QtCore.QRect(355, 490, 120, 180))
        self.mypuke_4.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_4.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_4.setAutoFillBackground(False)
        self.mypuke_4.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_4.setMidLineWidth(100)
        self.mypuke_4.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_4.setObjectName("mypuke_4")
        self.mypuke_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_5.setGeometry(QtCore.QRect(390, 490, 120, 180))
        self.mypuke_5.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_5.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_5.setAutoFillBackground(False)
        self.mypuke_5.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_5.setMidLineWidth(100)
        self.mypuke_5.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_5.setObjectName("mypuke_5")
        self.mypuke_6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_6.setGeometry(QtCore.QRect(425, 490, 120, 180))
        self.mypuke_6.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_6.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_6.setAutoFillBackground(False)
        self.mypuke_6.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_6.setMidLineWidth(100)
        self.mypuke_6.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_6.setObjectName("mypuke_6")
        self.mypuke_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_7.setGeometry(QtCore.QRect(460, 490, 120, 180))
        self.mypuke_7.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_7.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_7.setAutoFillBackground(False)
        self.mypuke_7.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_7.setMidLineWidth(100)
        self.mypuke_7.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_7.setObjectName("mypuke_7")
        self.mypuke_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_8.setGeometry(QtCore.QRect(495, 490, 120, 180))
        self.mypuke_8.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_8.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_8.setAutoFillBackground(False)
        self.mypuke_8.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_8.setMidLineWidth(100)
        self.mypuke_8.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_8.setObjectName("mypuke_8")
        self.mypuke_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_9.setGeometry(QtCore.QRect(530, 490, 120, 180))
        self.mypuke_9.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_9.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_9.setAutoFillBackground(False)
        self.mypuke_9.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_9.setMidLineWidth(100)
        self.mypuke_9.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_9.setObjectName("mypuke_9")
        self.mypuke_10 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_10.setGeometry(QtCore.QRect(565, 490, 120, 180))
        self.mypuke_10.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_10.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_10.setAutoFillBackground(False)
        self.mypuke_10.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_10.setMidLineWidth(100)
        self.mypuke_10.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_10.setObjectName("mypuke_10")
        self.mypuke_11 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_11.setGeometry(QtCore.QRect(600, 490, 120, 180))
        self.mypuke_11.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_11.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_11.setAutoFillBackground(False)
        self.mypuke_11.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_11.setMidLineWidth(100)
        self.mypuke_11.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_11.setObjectName("mypuke_11")
        self.mypuke_12 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_12.setGeometry(QtCore.QRect(635, 490, 120, 180))
        self.mypuke_12.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_12.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_12.setAutoFillBackground(False)
        self.mypuke_12.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_12.setMidLineWidth(100)
        self.mypuke_12.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_12.setObjectName("mypuke_12")
        self.mypuke_13 = QtWidgets.QGraphicsView(self.centralwidget)
        self.mypuke_13.setGeometry(QtCore.QRect(670, 490, 120, 180))
        self.mypuke_13.setMinimumSize(QtCore.QSize(120, 180))
        self.mypuke_13.setMaximumSize(QtCore.QSize(120, 180))
        self.mypuke_13.setAutoFillBackground(False)
        self.mypuke_13.setStyleSheet("border-image: url(:/.../puke/back.png);")
        self.mypuke_13.setMidLineWidth(100)
        self.mypuke_13.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.mypuke_13.setObjectName("mypuke_13")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(180, -10, 261, 201))
        self.graphicsView.setStyleSheet("border-image: url(:/.../logo4.png);")
        self.graphicsView.setObjectName("graphicsView")
        Startgame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Startgame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 23))
        self.menubar.setObjectName("menubar")
        Startgame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Startgame)
        self.statusbar.setObjectName("statusbar")
        Startgame.setStatusBar(self.statusbar)

        self.retranslateUi(Startgame)
        QtCore.QMetaObject.connectSlotsByName(Startgame)

    def retranslateUi(self, Startgame):
        _translate = QtCore.QCoreApplication.translate
        Startgame.setWindowTitle(_translate("Startgame", "亚瑟王の十三水-开始游戏"))
        self.buttonfendun.setText(_translate("Startgame", "自动分墩"))


import IMG
