# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '注册界面.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_window(object):
    def setupUi(self, register_window):
        register_window.setObjectName("register_window")
        register_window.resize(1280, 720)
        register_window.setMinimumSize(QtCore.QSize(1280, 720))
        register_window.setMaximumSize(QtCore.QSize(1280, 720))
        register_window.setStyleSheet("#register_window{\n"
                                      "border-image: url(:/image/background.png);\n"
                                      "}")
        self.centralwidget = QtWidgets.QWidget(register_window)
        self.centralwidget.setObjectName("centralwidget")
        self.login_background = QtWidgets.QLabel(self.centralwidget)
        self.login_background.setGeometry(QtCore.QRect(367, 230, 571, 401))
        font = QtGui.QFont()
        font.setFamily("哥特式字体")
        font.setPointSize(26)
        self.login_background.setFont(font)
        self.login_background.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_background.setStyleSheet("border-image: url(:/image/yangpizhi1.png);")
        self.login_background.setText("")
        self.login_background.setObjectName("login_background")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(227, 110, 911, 121))
        font = QtGui.QFont()
        font.setFamily("哥特式字体")
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.register_button = QtWidgets.QPushButton(self.centralwidget)
        self.register_button.setGeometry(QtCore.QRect(470, 540, 361, 51))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.register_button.setFont(font)
        self.register_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_button.setStyleSheet("font: 20pt \"华文新魏\";\n"
                                           "color: rgb(255, 255, 255);\n"
                                           "background-color: rgb(22, 155, 213);")
        self.register_button.setFlat(False)
        self.register_button.setObjectName("register_button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(687, 260, 101, 51))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(647, 310, 185, 16))
        self.line.setStyleSheet("border-top: 4px solid red; ")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.xue_hao = QtWidgets.QLineEdit(self.centralwidget)
        self.xue_hao.setGeometry(QtCore.QRect(470, 440, 361, 41))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        self.xue_hao.setFont(font)
        self.xue_hao.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.xue_hao.setObjectName("xue_hao")
        self.zhang_hao = QtWidgets.QLineEdit(self.centralwidget)
        self.zhang_hao.setGeometry(QtCore.QRect(470, 340, 361, 41))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        self.zhang_hao.setFont(font)
        self.zhang_hao.setObjectName("zhang_hao")
        self.deng_lu = QtWidgets.QPushButton(self.centralwidget)
        self.deng_lu.setGeometry(QtCore.QRect(507, 260, 101, 51))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(26)
        self.deng_lu.setFont(font)
        self.deng_lu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deng_lu.setFlat(True)
        self.deng_lu.setObjectName("deng_lu")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(467, 310, 185, 20))
        self.line_2.setStyleSheet("border-top: 2px solid white")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(317, 540, 128, 128))
        self.label_3.setStyleSheet("border-image: url(:/image/dunpai.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.mi_ma = QtWidgets.QLineEdit(self.centralwidget)
        self.mi_ma.setGeometry(QtCore.QRect(470, 390, 361, 41))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(14)
        self.mi_ma.setFont(font)
        self.mi_ma.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mi_ma.setObjectName("mi_ma")
        self.jwc_mima = QtWidgets.QLineEdit(self.centralwidget)
        self.jwc_mima.setGeometry(QtCore.QRect(470, 490, 361, 41))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        self.jwc_mima.setFont(font)
        self.jwc_mima.setEchoMode(QtWidgets.QLineEdit.Password)
        self.jwc_mima.setObjectName("jwc_mima")
        register_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(register_window)
        QtCore.QMetaObject.connectSlotsByName(register_window)

    def retranslateUi(self, register_window):
        _translate = QtCore.QCoreApplication.translate
        register_window.setWindowTitle(_translate("register_window", "亚瑟王の十三水"))
        register_window.setToolTip(_translate("register_window", "qign"))
        self.label.setText(_translate("register_window",
                                      "<html><head/><body><p><span style=\" font-weight:600; "
                                      "color:#e4e4e4;\">亚瑟王の十三水</span></p></body></html>"))
        self.register_button.setText(_translate("register_window", "立即注册"))
        self.label_2.setText(_translate("register_window", "注册"))
        self.xue_hao.setPlaceholderText(_translate("register_window", "请输入您的学号"))
        self.zhang_hao.setPlaceholderText(_translate("register_window", "请输入您的用户名"))
        self.deng_lu.setText(_translate("register_window", "登录"))
        self.mi_ma.setPlaceholderText(_translate("register_window", "请输入您的密码"))
        self.jwc_mima.setPlaceholderText(_translate("register_window", "请输入您的教务处密码"))


import backpict
