# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '登录界面.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(1280, 720)
        login_window.setMinimumSize(QtCore.QSize(1280, 720))
        login_window.setMaximumSize(QtCore.QSize(1280, 720))
        login_window.setStyleSheet("#login_window{\n"
                                   "border-image: url(:/image/background.png);\n"
                                   "}")
        self.centralwidget = QtWidgets.QWidget(login_window)
        self.centralwidget.setObjectName("centralwidget")
        self.login_background = QtWidgets.QLabel(self.centralwidget)
        self.login_background.setGeometry(QtCore.QRect(367, 230, 571, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_background.sizePolicy().hasHeightForWidth())
        self.login_background.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("哥特式字体")
        font.setPointSize(26)
        self.login_background.setFont(font)
        self.login_background.setStyleSheet("border-image: url(:/image/yangpizhi1.png);")
        self.login_background.setText("")
        self.login_background.setObjectName("login_background")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(227, 110, 911, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("哥特式字体")
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(470, 480, 361, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_button.sizePolicy().hasHeightForWidth())
        self.login_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.login_button.setFont(font)
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setStyleSheet("font: 20pt \"华文新魏\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(22, 155, 213);")
        self.login_button.setFlat(False)
        self.login_button.setObjectName("login_button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(507, 260, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(467, 310, 185, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setStyleSheet("border-top: 4px solid red; ")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.mi_ma = QtWidgets.QLineEdit(self.centralwidget)
        self.mi_ma.setGeometry(QtCore.QRect(470, 410, 361, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mi_ma.sizePolicy().hasHeightForWidth())
        self.mi_ma.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        self.mi_ma.setFont(font)
        self.mi_ma.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mi_ma.setObjectName("mi_ma")
        self.zhang_hao = QtWidgets.QLineEdit(self.centralwidget)
        self.zhang_hao.setGeometry(QtCore.QRect(470, 340, 361, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zhang_hao.sizePolicy().hasHeightForWidth())
        self.zhang_hao.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(16)
        self.zhang_hao.setFont(font)
        self.zhang_hao.setObjectName("zhang_hao")
        self.zhu_ce = QtWidgets.QPushButton(self.centralwidget)
        self.zhu_ce.setGeometry(QtCore.QRect(680, 260, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zhu_ce.sizePolicy().hasHeightForWidth())
        self.zhu_ce.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(26)
        self.zhu_ce.setFont(font)
        self.zhu_ce.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.zhu_ce.setTabletTracking(False)
        self.zhu_ce.setFlat(True)
        self.zhu_ce.setObjectName("zhu_ce")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(647, 310, 185, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setStyleSheet("border-top: 2px solid white")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(317, 540, 128, 128))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("border-image: url(:/image/dunpai.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        login_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "亚瑟王の十三水"))
        login_window.setToolTip(_translate("login_window", "qign"))
        self.label.setText(_translate("login_window",
                                      "<html><head/><body><p><span style=\" font-weight:600; "
                                      "color:#e4e4e4;\">亚瑟王の十三水</span></p></body></html>"))
        self.login_button.setText(_translate("login_window", "立即登录"))
        self.label_2.setText(_translate("login_window", "登录"))
        self.mi_ma.setPlaceholderText(_translate("login_window", "请在此输入您的密码"))
        self.zhang_hao.setPlaceholderText(_translate("login_window", "请在此输入您的用户名"))
        self.zhu_ce.setText(_translate("login_window", "注册"))


import backpict
